name: Build and Deploy Docker Images

on:
  push:
    branches:
      - test
      - prod
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Configure Docker insecure registries(master)
      if: github.ref == 'refs/heads/master'
      run: |
        echo '{ "insecure-registries" : ["102.88.47.20:5001"] }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        
    - name: Build and Push Docker Images(master)
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_BUILDKIT: 0
        COMPOSE_DOCKER_CLI_BUILD: 0
      run: |
        docker-compose -f docker-compose.yml build
        docker tag acunifiedportal 102.88.47.20:5001/acunifiedportal:${{ github.ref_name }}
        docker push 102.88.47.20:5001/acunifiedportal:${{ github.ref_name }}
   
    - name: Install the sshpass(master)
      if: github.ref == 'refs/heads/master'
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Configure Docker insecure registries(prod)
      if: github.ref == 'refs/heads/prod'
      run: |
        echo '{ "insecure-registries" : ["83.229.71.143:5001"] }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        
    - name: Build and Push Docker Images(prod)
      if: github.ref == 'refs/heads/prod'
      env:
        DOCKER_BUILDKIT: 0
        COMPOSE_DOCKER_CLI_BUILD: 0
      run: |
        docker-compose -f docker-compose.yml build
        docker tag acunifiedportal 83.229.71.143:5001/acunifiedportal:${{ github.ref_name }}
        docker push 83.229.71.143:5001/acunifiedportal:${{ github.ref_name }}

    - name: Install the sshpass(prod)
      if: github.ref == 'refs/heads/prod'
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy to Test Server
      if: github.ref == 'refs/heads/test'
      run: |
        ssh hp@102.88.47.20 '
          docker pull localhost:5001/acunifiedportal:test
          docker stop acunifiedportal-test || true
          docker rm acunifiedportal-test || true
          docker run -d --name acunifiedportal-test -p 80:80 localhost:5001/acunifiedportal:test
        '
            
    - name: Deploy to Production Server(prod)
      if: github.ref == 'refs/heads/prod'
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PRIVATE_PW_PROD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@83.229.71.143 '
          docker pull localhost:5001/acunifiedportal:prod
          docker stop acunifiedportal-prod || true
          docker rm acunifiedportal-prod || true
          docker run -d --name acunifiedportal-prod -v /root/DockerContainers/data/certs:/app/certificates -v /root/DockerContainers/data/documents:/app/wwwroot/Applications -p 80:80 -p 443:443 -e ASPNETCORE_HTTPS_PORT=443  localhost:5001/acunifiedportal:prod
        '

    - name: Deploy to Master Branch Server
      if: github.ref == 'refs/heads/master'
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PRIVATE_PW }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no hp@102.88.47.20 '
          docker pull localhost:5001/acunifiedportal:master
          docker stop acunifiedportal-master || true
          docker rm acunifiedportal-master || true
          docker run -d --name acunifiedportal-master -v /home/hp/Documents/DockerContainers/data/certs:/app/certificates -v /home/hp/Documents/DockerContainers/data/documents:/app/wwwroot/Applications -p 80:80 -p 443:443 -e ASPNETCORE_HTTPS_PORT=443 localhost:5001/acunifiedportal:master
        '
